name: Auto Push Protection

on:
  push:
    branches:
      - main

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Confirm presença simbólica
        run: echo "Protegido por RAFAELIA ∞ sob Convenção de Berna"